name: build-publish-npmjs

on:
  repository_dispatch:
    types:
      - dispatch-build-publish-npmjs

  workflow_dispatch:
    inputs:
      pnpm-run-test:
        description: "pnpm run test:run"
        required: false
        type: string
        default: 'true'
      pnpm-publish-args:
        description: "pnpm publish args"
        required: false
        type: string
        default: ~
      node-version:
        description: "node version"
        required: false
        type: string
        default: '20'

jobs:
  configure:
    uses: jr200/github-action-templates/.github/workflows/preconfigure.yml@main
    with:
      event_name: ${{ toJson(github.event_name) }}
      event: ${{ toJson(github.event) }}

  main:
    needs: configure
    uses: jr200/github-action-templates/.github/workflows/build_publish_npmjs.yml@main
    with:
      pnpm-run-test: ${{ fromJson(needs.configure.outputs.context).pnpm-run-test }}
      pnpm-publish-args: ${{ fromJson(needs.configure.outputs.context).pnpm-publish-args }}
      node-version: ${{ fromJson(needs.configure.outputs.context).node-version }}
    secrets:
      npmjs_api_token: ${{ secrets.NPMJS_API_TOKEN }}


  spawn-workflow:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - id: prepare_payload
        run: |
          cat <<EOF > old_payload.json
          ${{ toJson(github.event.client_payload) }}
          EOF
          
          cat old_payload.json | jq '. + {"npmjs_run_id": "${{ github.run_id }}"}' > new_payload.json
          echo "payload=$(cat new_payload.json | jq -c '.')" >> $GITHUB_OUTPUT

      - name: dispatch-next-workflow
        uses: peter-evans/repository-dispatch@v3
        if: github.event_name != 'workflow_dispatch'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: dispatch-publish-release
          client-payload: ${{ steps.prepare_payload.outputs.payload }}